name: multi_tap_action
description: "A Flutter package that allows you to detect a specific number of taps on a widget and perform a custom action in response."
version: 1.0.0
repository: "https://github.com/sawongam/multi_tap_action/"

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: